# Codecov configuration for Ohlala SmartOps
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2% # Allow 2% drop from target
        informational: true # Don't fail PR, just inform
    patch:
      default:
        target: 80%
        threshold: 2%
        informational: true # Don't fail PR during migration phase

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
