"""Data models for Ohlala SmartOps.

This package contains Pydantic models for conversation context, messages,
command requests/responses, approval workflows, and adaptive cards.
"""

from ohlala_smartops.models.approvals import (
    ApprovalAction,
    ApprovalDecision,
    ApprovalLevel,
    ApprovalRequest,
    ApprovalStatus,
    ApprovalWorkflow,
)
from ohlala_smartops.models.cards import (
    ApprovalCardData,
    CardAction,
    CardActionType,
    CardChoice,
    CardColor,
    CardElementType,
    CardFact,
    CardSize,
    CardSubmission,
    CardTemplate,
    CommandFormData,
    InstanceActionCardData,
    MetricsCardData,
)
from ohlala_smartops.models.command_tracking import (
    CommandTrackingInfo,
    SSMCommandStatus,
    WorkflowInfo,
)
from ohlala_smartops.models.conversation import (
    ChannelInfo,
    ConversationContext,
    ConversationState,
    ConversationType,
    TeamInfo,
    UserInfo,
    UserRole,
)
from ohlala_smartops.models.messages import (
    Activity,
    ActivityType,
    Attachment,
    AttachmentType,
    ChannelAccount,
    ConversationAccount,
    Entity,
    InvokeResponse,
    MessageResponse,
    TeamsChannelData,
)
from ohlala_smartops.models.requests import (
    AIInterpretation,
    CloudWatchMetricsRequest,
    CommandPriority,
    CommandRequest,
    CommandResponse,
    CommandStatus,
    CommandType,
    CostRequest,
    EC2InstanceAction,
    EC2InstanceFilter,
    NaturalLanguageRequest,
    SSMCommandRequest,
    SSMSessionRequest,
)

__all__ = [
    # Request models
    "AIInterpretation",
    # Message models
    "Activity",
    "ActivityType",
    # Approval models
    "ApprovalAction",
    # Card models
    "ApprovalCardData",
    "ApprovalDecision",
    "ApprovalLevel",
    "ApprovalRequest",
    "ApprovalStatus",
    "ApprovalWorkflow",
    "Attachment",
    "AttachmentType",
    "CardAction",
    "CardActionType",
    "CardChoice",
    "CardColor",
    "CardElementType",
    "CardFact",
    "CardSize",
    "CardSubmission",
    "CardTemplate",
    "ChannelAccount",
    # Conversation models
    "ChannelInfo",
    "CloudWatchMetricsRequest",
    "CommandFormData",
    "CommandPriority",
    "CommandRequest",
    "CommandResponse",
    "CommandStatus",
    "CommandTrackingInfo",
    "CommandType",
    "ConversationAccount",
    "ConversationContext",
    "ConversationState",
    "ConversationType",
    "CostRequest",
    "EC2InstanceAction",
    "EC2InstanceFilter",
    "Entity",
    "InstanceActionCardData",
    "InvokeResponse",
    "MessageResponse",
    "MetricsCardData",
    "NaturalLanguageRequest",
    "SSMCommandRequest",
    "SSMCommandStatus",
    "SSMSessionRequest",
    "TeamInfo",
    "TeamsChannelData",
    "UserInfo",
    "UserRole",
    "WorkflowInfo",
]
